# permissions for end users to view gcprolebindings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gcprolebinding-viewer-role
rules:
- apiGroups:
  - tempiam.tempiam.io
  resources:
  - gcprolebindings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tempiam.tempiam.io
  resources:
  - gcprolebindings/status
  verbs:
  - get
